dobrowest/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from dobrowest import settings


urlpatterns = [
                url(r'^accounts/', include('allauth.urls')),
                url(r'^admin/', include(admin.site.urls)),
                url(r'^admin_tools/', include('admin_tools.urls')),
                url(r'^facts/', include('facts.urls', namespace = 'facts')),
                url(r'^ideas/', include('ideas.urls', namespace = 'ideas')),
                url(r'^invitations/', include('invitations.urls')),
                url(r'^', include('facts.urls')),
            ]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
# patterns('',
# (r'^%s(?P<path>.*)$' % settings.STATIC_URL.lstrip('/'), 'django.views.static.serve',
#                   { 'document_root': settings.STATIC_ROOT }),
#          (r'^%s(?P<path>.*)$' % settings.MEDIA_URL.lstrip('/'), 'django.views.static.serve',
#           { 'document_root': settings.MEDIA_ROOT }),
#                               )

facts/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

urlpatterns = [
    #url(r'^facts/', 'ideas.views.show_facts'),
    #url(r'^get/(?P<facts_id>\d+)/(?P<ideas_page>\d+)/$', 'facts.views.show_ideas'),
    # url(r'^addlike/(?P<id_idea>\d+)/(?P<like_id>\d+)/$','ideas.views.addlike', name = 'addlike'),
    #url(r'^addidea/(?P<id_fact>\d+)/(?P<ideas_page>\d+)/$','facts.views.create_idea'),

    #url(r'^page/(?P<page>\d+)/$', 'facts.views.show_list'),  # newone
    url(r'^id/(?P<pk>\d+)/$', 'facts.views.show_detail', name='detail'),  # newone
    #url(r'^fact/(?P<pk>\d+)/(?P<page>\d+)/$', 'facts.views.show_detail','detail-by-page'),  # newone
    url(r'^$', 'facts.views.show_list'),                     # newone

]

ideas/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url


urlpatterns = [
	#url(r'^ideas/all/$', 'ideas.views.blogShowAll'),
	#url(r'^ideas/get/(?P<id_blog>\d+)/(?P<page_number>\d+)/$', 'ideas.views.blog'),
	#url(r'^addlike/(?P<id_blog>\d+)/(?P<id_page>\d+)/$', 'ideas.views.addlike', name='addlike'),
	#url(r'^', 'ideas.views.addlike'),
	#url(r"^add/$", IdeasCreate.as_view(), name='add'),
	url(r"^create/$", 'ideas.views.icreate', name = 'create'),
	url(r'^vote/(?P<pk>\d+)/(?P<like_id>\d+)/$', 'ideas.views.ivote', name = 'vote'),
	url(r'^public/(?P<pk>\d+)/$', 'ideas.views.ipublic', name = 'public'),
	url(r'^edit/(?P<pk>\d+)/$', 'ideas.views.iedit', name = 'edit'),
	url(r'^delete/(?P<pk>\d+)/$', 'ideas.views.idelete', name = 'delete'),
	#url(r'^page/(?P<page>\d+)/$', 'ideas.views.show_list'),
    #url(r'^', 'ideas.views.show_dashboad'),

]

vsekdobru/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from vsekdobru import settings


urlpatterns = [
                url(r'^accounts/', include('allauth.urls')),
                url(r'^admin/', include(admin.site.urls)),
                url(r'^admin_tools/', include('admin_tools.urls')),
                url(r'^facts/', include('facts.urls', namespace = 'facts')),
                url(r'^ideas/', include('ideas.urls', namespace = 'ideas')),
                url(r'^invitations/', include('invitations.urls')),
                url(r'^filldb/', 'vsekdobru.test.fillDB', name = 'test'),
                url(r'^', include('facts.urls')),
            ]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
# patterns('',
# (r'^%s(?P<path>.*)$' % settings.STATIC_URL.lstrip('/'), 'django.views.static.serve',
#                   { 'document_root': settings.STATIC_ROOT }),
#          (r'^%s(?P<path>.*)$' % settings.MEDIA_URL.lstrip('/'), 'django.views.static.serve',
#           { 'document_root': settings.MEDIA_ROOT }),
#                               )

ideas/models.py
# -*- coding: utf-8 -*-
from django.core import urlresolvers
from django.core.exceptions import ValidationError
from django.db import models

from vsekdobru.utils import CustomImageFields
from facts.models import Facts
from accounts.models import CustomUser




#--------------------------------------------------------------------
#
# Описываем поля базы данных типов тегов добавляемых одобрений
#
#--------------------------------------------------------------------
class Tags(models.Model):
    class Meta():
        db_table = "dobro_tags"  # Название таблицы
        verbose_name = verbose_name_plural = u"Метки идей"

    name = models.CharField(verbose_name = u"Метка", max_length = 20, unique = True)
    desc = models.TextField(verbose_name = u"Описание", blank = True, default = '')

    def __unicode__( self ):
        return u'{display_name}'.format(display_name = self.name)

#--------------------------------------------------------------------
#
# Описываем поля базы данных категорий добавляемых новостей
#
#--------------------------------------------------------------------
class Category(models.Model):
    class Meta():
        db_table = "dobro_category"  # Название таблицы
        verbose_name = verbose_name_plural = u"Разделы публикаций"

    name = models.CharField(verbose_name = u"Категория", max_length = 20, unique = True)
    desc = models.TextField(verbose_name = u"Описание", blank = True, default = '')

    def __unicode__( self ):
        return u'{display_name}'.format(display_name = self.name)

#--------------------------------------------------------------------
#
# Описываем поля базы данных одобренных новостей
#
#--------------------------------------------------------------------
class Ideas(models.Model):
    class Meta():
        db_table = "dobro_ideas"  # Название таблицы
        verbose_name = verbose_name_plural = u"Добрые идеи"

    TYPE_OF_NEWS = ((1, u'Тема'),
                    (2, u'Статья'),
                    (3, u'Комментарий'))
    type = models.IntegerField(choices = TYPE_OF_NEWS, default = 1, verbose_name = u"Тип идеи",
                               help_text = u'Выбирите тип Вашей идеи')

    date_create = models.DateTimeField(verbose_name = u"Дата создания", auto_now_add = True)
    date_update = models.DateTimeField(verbose_name = u"Дата обновления", auto_now = True)
    text = models.TextField(verbose_name = u"Ваша идея", blank = False,
                            help_text = u'Введите пожалуйста Вашу идею по поводу статьи, смысл которой отвечал бы трем основным принципам проекта: Добро, Радость, Развитие')
    foto = CustomImageFields(verbose_name = u"Фото", blank = True, )
    published = models.BooleanField(verbose_name = u"Опубликована", blank = True, default = False)

    dobro_like = models.IntegerField(verbose_name = u"Доброта", default = 0, help_text = u'Здесь есть добро!')
    radost_like = models.IntegerField(verbose_name = u"Радость", default = 0, help_text = u'Здесь есть радость!')
    razvitie_like = models.IntegerField(verbose_name = u"Развитие", default = 0, help_text = u'Здесь есть развитие!')

    # Указатель на категорию новостей
    # как "много в DobroNews к одному в Category"
    category = models.ForeignKey(Category, verbose_name = u"Категория новостей", blank = False)

    # Указатель на автора статьи
    # как "много в DobroNews к одному в Facts"
    author = models.ForeignKey(CustomUser, verbose_name = u"Автор статьи", blank = False)

    # Указатель на принадлежность к старой статье
    # как "много в DobroNews к одному в Facts"
    fact = models.ForeignKey(Facts, verbose_name = u"Источник статьи", blank = False)

    # Указатель тегов/категорий новостей,
    # как "много в DobroNews к много в Tags"
    tag = models.ManyToManyField(Tags, verbose_name = u"Метки статьи", blank = True, default = None)


    def get_absolute_url( self ):
        return urlresolvers.reverse('ideas:edit', args = (self.pk,))

    def get_tags_list(self):
        return u", ".join([tag.name for tag in self.tag.all()])

    def get_author_name(self):
        return CustomUser.objects.get(id = self.author_id).username

    def get_idea_type(self):
        return self.get_type_display()


    def __unicode__( self ):
        return u'{display_name}'.format(display_name=self.text)

    def clean_text(self):
        if self.text.isdigit():
            raise ValidationError(u'Пожалуйста, введите текст.')

    def clean_category(self):
        if not self.category:
            raise ValidationError(u'Подскажите пожалуйста, к какой категории относится Ваша идея?')

#--------------------------------------------------------------------
#
#   Описываем поля базы данных для регистрации голосов пользователей
#
#--------------------------------------------------------------------
class UserVoices(models.Model):

    class Meta():
        db_table = "dobro_uservoices"  # Название таблицы
        verbose_name = verbose_name_plural = u"Голосование"

    user = models.ForeignKey(CustomUser, verbose_name = u"Индификатор пользователя", db_index = True, blank = False)
    ideas = models.ForeignKey(Ideas, verbose_name = u"Индификатор идеи", db_index = True, blank = False)
    dobro = models.BooleanField(verbose_name = u"Принцип добра", default = 0)
    razvitie = models.BooleanField(verbose_name = u"Принцип развития", default = 0)
    radost = models.BooleanField(verbose_name = u"Принцип радости", default = 0)

ideas/forms.py
# -*- coding: utf-8 -*-
'''
	   Проект: vsekdobru
	   Имя файла: forms.py
	   Дата создания: 16.04.15
	   Время создания: 19:40
	   Автор проекта: adam
'''
from django.forms import ModelForm, widgets

from ideas.models import Ideas
from vsekdobru.utils import ImageWidget

#-----------------------------------------------------
#
#   Класс описывает форму ввода ...
#
#-----------------------------------------------------
#

class IdeasForm(ModelForm):
	'''
	#	Класс описывает форму ввода идей
	'''
	class Meta():
		model = Ideas
		fields = ['text', 'type','category', 'fact', 'foto', 'tag']
		widgets = {
		'fact': widgets.HiddenInput,
		'foto': ImageWidget,  # 'text': PagedownWidget,
		'text': widgets.Textarea(attrs = { 'placeholder': u'Добавьте добрую идею!' })
		}

ideas/views.py
# -*- coding: utf-8 -*-
from django.contrib import auth
from django.core.exceptions import ObjectDoesNotExist
from django.http import Http404
from django.shortcuts import redirect
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from accounts.models import CustomUser
from vsekdobru.utils import UserPassesTestMixin
from facts.models import Facts
from ideas.forms import IdeasForm
from ideas.models import Ideas


TEMPLATE_IDEAS = 'dobroboad.html'


def get_rollback_url( request ):
    return request.META['HTTP_REFERER']


# ------------------------------------------------------------------
#
#   Отображает опубликованные добрые идеи
#
#------------------------------------------------------------------
class Dobroboad(UserPassesTestMixin, ListView, ):
    model = Ideas
    template_name = TEMPLATE_IDEAS
    paginate_by = 2
    queryset = Ideas.objects.filter(published = True).order_by('type')

show_dashboad = Dobroboad.as_view()

# ------------------------------------------------------------------
#
# Обрабатывает создание новых идей
#
# ------------------------------------------------------------------
class IdeasCreate(UserPassesTestMixin, CreateView):
    model = Ideas
    form_class = IdeasForm
    http_method_names = ['post']
    template_name = 'idea_to_create.html'
    decorators = ['login_required']
    #succes_url = '/success/'

    def form_valid( self, form ):
        id = self.request.session['fact_id']
        author = auth.get_user(self.request).id
        try:
            idea = form.save(commit = False)
            img = self.request.FILES.get('foto')
            if img:
                idea.foto = img
            idea.fact = Facts.objects.get(id = id)
            idea.author = CustomUser.objects.get(pk = author)
            form.save()
        except Exception as e:
            return self.form_invalid(form)
        return redirect(get_rollback_url(self.request))
        # return redirect(reverse('facts:detail', args = [id]))


icreate = IdeasCreate.as_view()


class IdeaEdit(UserPassesTestMixin, UpdateView):
    model = Ideas
    form_class = IdeasForm
    template_name = 'idea_to_edit.html'
    decorators = ['login_required', ]

    # def dispatch(self, request, *args, **kwargs):
    #        self.get_context_data(kwargs)
    #        return super(IdeaEdit,self).dispatch(request)


    def get_context_data( self, **kwargs ):
        ret = super(IdeaEdit, self).get_context_data(**kwargs)
        ret['idea_id'] = self.kwargs['pk']
        url = get_rollback_url(self.request)
        #self.request.session['urlback'] = "/".join(url.split('/')[-4:])
        self.request.session['urlback'] = url
        return ret

    def get_success_url( self ):
        ret = self.request.session['urlback']

        return ret
        #decorators = 'login_required'

        #def get_initial( self ):
        #    # GET method is allowed, so we need to have some antispam protection
        #    article = self.object.fact
        #    referer = urlparse(self.request.META.get('HTTP_REFERER', ''))
        #    if article.id not in referer.path:  # /slug/
        #        raise PermissionDenied()
        #    return self.initial

        #def form_invalid(self, form):
        #    return super(IdeaEdit, self).form_invalid(form)


iedit = IdeaEdit.as_view()


def Iidelete( request, pk ):
    '''
        Удаяем переданную в pk запись
    '''
    resp = redirect(request.META['HTTP_REFERER'])
    try:
        ideas = Ideas.objects.get(id = pk)
        if ideas.author.username == auth.get_user(request).username:
            ideas.delete()
        return resp
    except ObjectDoesNotExist:
        raise Http404


def dialog_yes_no( request, answer ):
    pass

class IdeaDelete(UserPassesTestMixin, DeleteView):
    model = Ideas
    form_class = IdeasForm
    template_name = 'idea_to_delete.html'
    decorators = ['login_required']

    def get_context_data( self, **kwargs ):
        ret = super(IdeaDelete, self).get_context_data(**kwargs)
        url = get_rollback_url(self.request)
        self.request.session['urlback'] = "/".join([x for x in url.split('/') if not '?' in x])
        return ret

    def get_success_url( self ):
        ret = self.request.session['urlback']
        return ret


idelete = IdeaDelete.as_view()
# ------------------------------------------------------------------
#
# Обрабатывает голосование за идею по трем принципам
#
# ------------------------------------------------------------------
def ivote( request, pk, like_id ):
    resp = redirect(request.META['HTTP_REFERER'])  # get_url_from_session(request))
    like_id = int(like_id)
    try:
        # if not id_idea in request.COOKIES:
        ideas = Ideas.objects.get(id = pk)
        if like_id == 1:
            ideas.dobro_like += 1
        elif like_id == 2:
            ideas.radost_like += 1
        elif like_id == 3:
            ideas.razvitie_like += 1

        ideas.save()
        #resp.set_cookie(id_blog, "test")
        return resp  #redirect('/facts/get/1/1/')
        #else:
        #    return redirect('/')
    except ObjectDoesNotExist:
        raise Http404


# ------------------------------------------------------------------
#
# Обрабатывает публикацию новых идей
#
# ------------------------------------------------------------------
def ipublic( request, pk ):
    resp = redirect(request.META['HTTP_REFERER'])  # get_url_from_session(request))
    try:
        ideas = Ideas.objects.get(id = pk)
        ideas.published = False if ideas.published else True
        ideas.save()
        return resp
    except ObjectDoesNotExist:
        raise Http404

ideas/templates/dobroboad.html
{% load staticfiles %}
{% csrf_token %}
{% load pagination_tags %}
{% autopaginate ideas_list 2 %}
{% block ideas_block %}

    <div class="row">
        <div class="large-1 large-offset-0  columns">
            <div class="pagination">{% paginate %} </div>
        </div>
        <div class="large-10 large-offset-1  columns">
            {% for idea in ideas_list %}
                    <p>Дата добавления: {{ idea.date_create|date:"d.m.Y в H:i" }}<br>
                    Дата обновления: {{ idea.date_update|date:"d.m.Y в H:i" }}<br>
                    Автор: {{ idea.get_author_name }}<br>
                    Тип: {{ idea.get_idea_type }}<br>
                    Категории: {{ idea.get_tags_list }}<br>
                    Фото:   {{ idea.foto }}<br>
                    Текст: {{ idea.text|safe }} </p>
            {% empty %}
                <p>Новых идей не обнаружено :(</p>
                <hr>
            {% endfor %}
        </div>


    </div>
{% endblock %}

ideas/templates/idea_create.html
{% extends 'main.html' %}
{% block idea_create %}
    {% include 'idea_form.html' %}
{% endblock %}

ideas/templates/idea_form.html
{% if username %}
    <div class="comment-form-container">
        <form class="comment-form" method="post" enctype="multipart/form-data" action="{% url 'ideas:create' %}">
            <div style="color: red;">{{ form.errors }}</div>
            {% csrf_token %}
            {{ success_message }}
            {% include 'fields.html' %}
            <input type="submit" class='button' value="Добавить идею">
        </form>
    </div>
<hr>
{% endif %}

ideas/templates/idea_to_create.html
{% extends 'main.html' %}
{% block idea_create %}
    {% include 'idea_form.html' %}
{% endblock %}

ideas/templates/idea_to_delete.html
{% extends 'main.html' %}
{% block idea_delete %}
    <form action="" method="post">
        {% csrf_token %}
        <p>Вы уверены, что хотите удалить "{{ object }}"?</p>
        <a class="button" href="{% url "detail" object.fact_id %}">Отменить</a>
        <input class="button" type="submit" value="Удалить"/>

    </form>
{% endblock %}

ideas/templates/idea_to_edit.html
{% extends 'main.html' %}
{% block idea_edit %}
    <div class="comment-form-container">
        <form class="comment-form" method="post" enctype="multipart/form-data" action="{% url 'ideas:edit' idea_id %}">
            <div style="color: red;">{{ form.errors }}</div>
            {% csrf_token %}
            {% include 'fields.html' %}
            <input type="submit" class='button' value="Обновить идею">
        </form>
    </div>
    <hr>
{% endblock %}

ideas/templates/ideas_list.html
{% load staticfiles %}
{% load pagination_tags %}
{% autopaginate ideas_list 2 %}
{% static 'img/no-photo-big.gif' as nopic %}
{% block ideas_block %}
    <div class="row">
        <div class="large-0 large-offset-0  columns">
            <div class="pagination">{% paginate %} </div>
        </div>
        <div class="large-10 large-offset-0  columns">
            {% for idea in ideas_list %}
                <p>Дата добавления: {{ idea.date_create|date:"d.m.Y в H:i" }}<br>
                    Дата обновления: {{ idea.date_update|date:"d.m.Y в H:i" }}<br>
                    Автор: {{ idea.get_author_name }}<br>
                    Тип: {{ idea.get_idea_type }}<br>
                    Категории: {{ idea.get_tags_list }}<br>
                    Фото: <br>
                    {% if idea.foto %}
                        {% load thumbnail %}
                        {% thumbnail idea.foto.path "2000x2000" as big %}
                            {% thumbnail idea.foto.path "350x200" padding_color="#aabbbd3" padding=True crop="top" as small %}
                                <a href="{{ big.url }}"><img style="margin:{{ small|margin:"200x200" }}"
                                                             src="{{ small.url }}"></a>
                            {% empty %}
                                {% thumbnail nopic.url "350x200" as np %}
                                    <a href="{% url 'ideas:edit' idea.id %}" class='golink'><img src="{{ np.url }}"></a>
                                {% endthumbnail %}
                            {% endthumbnail %}
                        {% endthumbnail %}
                    {% else %}
                        <a href="{% url 'ideas:edit' idea.id %}" class='golink'><img src="{{ nopic }}"></a>
                    {% endif %}
                    <br>
                    Текст: {{ idea.text|safe }}
                </p>
                {% if username %}
                    <a href="{% url 'ideas:vote' idea.id 1 %}"><img src="{% static "dobro_like.jpg" %}" width="30px"
                                                                    height="40px"></a>{{ idea.dobro_like }}
                    <a href="{% url 'ideas:vote' idea.id 2 %}"><img src="{% static "radost_like.jpg" %}" width="30px"
                                                                    height="40px"></a>{{ idea.radost_like }}
                    <a href="{% url 'ideas:vote' idea.id 3 %}"><img src="{% static "razvitie_like.jpg" %}" width="30px"
                                                                    height="40px"></a>{{ idea.razvitie_like }}

                    <a href="{% url 'ideas:edit' idea.id %}" class='button'>Редактировать</a>
                    <a href="{% url 'ideas:delete' idea.id %}" class='button'>Удалить</a>

                    {% if idea.published %}
                        <a href="{% url 'ideas:public' idea.id %}" class='button'>Снять с публикации</a>
                    {% else %}
                        <a href="{% url 'ideas:public' idea.id %}" class='button'>Опубликовать</a>
                    {% endif %}
                {% endif %}
                <hr>
            {% empty %}
                <p>Новых идей не обнаружено :(</p>
            {% endfor %}
        </div>
    </div>
{% endblock %}